### ISSUE TITLE
Please publish 2.1.5

### ISSUE THREAD

**Issue by kmalakoff** [Semantic-Org/Semantic-UI-CSS#15]
https://github.com/Semantic-Org/Semantic-UI/releases/tag/2.1.5

**Comment by jlukic** [comment]
Done

**Comment by kmalakoff** [comment]
@jlukic thank you! 

It doesn't seem to be updated on npm: https://www.npmjs.com/package/semantic-ui-css

**Comment by jlukic** [comment]
Ah yes, need to run another script.. ill getcha tomorrow
