### ISSUE TITLE
dist.zip in project root is outdated

### ISSUE THREAD

**Issue by frickenate** [Semantic-Org/Semantic-UI-CSS#22]
Now that I look at the directory listing of this repository a second time, I see all the necessary files are directly part of the repository. But there is the strange `dist.zip` file in the root directory which is the first file I had noticed the first time around. I unzipped this and used the contents - which turns out to contain an outdated copy of version `2.0.0`.

The very existence of this repo is odd considering that the core [Semantic-UI](https://github.com/Semantic-Org/Semantic-UI/tree/master/dist) repository already contains a `dist/` directory containing exactly what is being provided here (though already desynced as this repo has `2.2.3` whereas core dist has `2.2.4`).

In any case, would recommend updating `dist.zip` to contain the same version as the outer layer, if not possible to remove the file entirely for backwards-compatibility. I got burned thinking there were bugs that have long been fixed in `2.0.x+`.

**Comment by jlukic** [comment]
I've removed the zip, not sure when it got there, but it was unintentional. This repo is built by deploy script.
