### ISSUE TITLE
Unable to load semantic-ui-css with extract text plugin webpack

### ISSUE THREAD

**Issue by nitish24p** [Semantic-Org/Semantic-UI-CSS#28]
I'm trying to import semantic-ui-css via webpack into my script and i keep getting the error
```
Unexpected character '@' (11:0)
You may need an appropriate loader to handle this file type.
```
I am using the extract text plugin to separate my sass into a file of its own
```javascript
// Import file in main file
import 'semantic-ui-css/semantic.min.css';

export default class MainContainer extends React.Component {
 ...
}
```

webpack config
```Javascript
// webpack.config.js
const webpack = require('webpack');
const path = require('path');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
  entry:  {
    main: __dirname + '/client/main-container.js',
    vendors: [
      'react',
      'react-dom',
      'redux',
      'react-router',
      'semantic-ui-react',
      'axios',
      'react-router-redux',
      'react-redux-toastr',
      'react-redux'
    ]
  },
  output: {
    path: './client/build',
    filename: 'bundle-[chunkhash].js',
  },
  stats: {},
  module: {
    loaders: [
      {
        test: /\.js/,
        exclude: /node_modules/,
        loader: 'babel',
        include: __dirname + '/client',
        resolve: {
          extensions: ['', '.js', '.jsx'],
        },
      },
      {
        test: /\.scss/,
        include: __dirname + '/client',
        loader: ExtractTextPlugin.extract('style', 'css!sass')
      },
      {
        test: /\.css/,
        include: __dirname + '/client',
        loader: ExtractTextPlugin.extract('style', 'css-loader')
      }
    ],
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors-[chunkhash].js', Infinity),
    new ExtractTextPlugin("[name]-[chunkhash].css"),
    function() {
      this.plugin("done", function(stats) {
        require("fs").writeFileSync(
          path.join(__dirname, "client", "build", "stats.json"),
          JSON.stringify(stats.toJson().assetsByChunkName));
    });
    },
    new CleanWebpackPlugin(['build'], {
      verbose: true,
      dry: false,
      root: __dirname + '/client',
    }),
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify(process.env.NODE_ENV) || JSON.stringify('dev')
      }
    }),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin()
  ]
};


```

any help would be great.

**Comment by DanHarman** [comment]
I'm learning webpack at the moment, and using as my basis a template from `https://github.com/aspnet/JavaScriptServices`. Anyway with this template, creating a react redux app, by adding the following line into my vendors array, it works fine. It may or may not help you :)

`                'semantic-ui-css/semantic.min.css',`

**Comment by manigandham** [comment]
Try this instead so your loaders are properly called:

      {
        test: /\.scss/,
        include: __dirname + '/client',
        loader: ExtractTextPlugin.extract('style', 'css-loader', 'sass-loader')
      }

And do you have `sass-loader` (and `node-sass`) installed?

**Comment by chainlink** [comment]
Having the same issue 
```webpack: Failed to compile.
/Users/kyle/Documents/reactql-app/node_modules/semantic-ui-css/semantic.css:11
@import url('https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');
^```

**Comment by JamesRamm** [comment]
Similar issue here. This is when following option '3' in the docs for loading the semantic ui css:
https://react.semantic-ui.com/usage#semantic-ui-package

My `index.jsx`:

```
import React from 'react';
import {render} from 'react-dom';

import '../semantic/dist/semantic.min.css';

class App extends React.Component {
  render () {
    return <p> Hello React!</p>;
  }
}

render(<App/>, document.getElementById('app'));
```

And my webpack.config.js:

```
var webpack = require('webpack');
var path = require('path');

var BUILD_DIR = path.resolve(__dirname, 'static/js');
var APP_DIR = path.resolve(__dirname, 'app');

var config = {
    entry: APP_DIR + '/index.jsx',
    output: {
        path: BUILD_DIR,
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.jsx?/,
                include: APP_DIR,
                loader: 'babel-loader?presets[]=stage-0'
            },
            {
                test: /\.css$/,
                loader: 'style-loader!css-loader'
            },
        ]
    }
};

module.exports = config;
```

I get a bunch of errors relating to font/icon files, e.g.:

```
ERROR in ./semantic/dist/themes/default/assets/fonts/icons.svg
Module parse failed: /home/james/repos/tuclient/semantic/dist/themes/default/assets/fonts/icons.svg Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

The examples for using webpack dont go beyond loading the CSS files from a CDN - it would be helpful to have some guidance on using the package with webpack & what loaders are necessary

**Comment by JamesRamm** [comment]
Adding `url-loader` to the config solves the issue for me:

```
{
  test: /\.(png|woff|woff2|eot|ttf|svg)$/,
  loader: 'url-loader?limit=100000'
}
```
And you need to `npm i url-loader file-loader -S`

**Comment by manigandham** [comment]
The errors are pretty standard, it means that webpack doesnt understand the file type and cant parse the contents. The full `semantic-ui` package actually works well with webpack, I'll post a guide about setting it all up later.

@chainlink you should post your webpack config for troubleshooting

**Comment by staxval** [comment]
Had the same issue with using semantic-ui-css module and finally realised that the problem was in excluding **node_modules** folder from working dirs of css loader. Just make shure that your config allows css-loader to handle **node_modules/semantic-ui-css**. Hope this will help anybody.

**Comment by johnnykoo84** [comment]
Hello all, I have been struggling with the similar issue.. not able to parse module, unexpected char '@'
BTW, which version of webpack is everybody using? I happen to use webpack^3.3.0, not sure if this can be a problem. 

Here is my webpack code, and I don't really know what I am doing after hours of searching the right solution. I'd really appreciate your insights...

`
const webpack = require('webpack');
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const extractCSS = new ExtractTextPlugin('semantic/semantic.min.css');
const autoprefixer = require('autoprefixer');

module.exports = {

  entry: [
    path.resolve('./client/index.js'),
    'webpack-dev-server/client?http://0.0.0.0:3001',
    'webpack/hot/only-dev-server'
  ],

  output: {
    path: path.join(__dirname, 'public'),
    filename: 'bundle.js'
  },

  resolve: {
    extensions: ['.js', '.jsx', '.css']
  },

  devServer: {
    hot: true,
    filename: 'bundle.js',
    publicPath: '/',
    historyApiFallback: true,
    contentBase: './public',
    proxy: {
        "*": "http://localhost:3000"
    }
  },

    plugins: [
      new webpack.HotModuleReplacementPlugin(), // Enable HMR
      new webpack.NoEmitOnErrorsPlugin(),
      extractCSS,
      new webpack.LoaderOptionsPlugin({ options: { postcss: [ autoprefixer ] } })
    ],

  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        include: path.join(__dirname, 'client'),
        use: ['react-hot-loader', 'babel-loader?' + JSON.stringify({
          cacheDirectory: true,
          presets: ['es2015', 'react']
        })],
      },
      {
        test: /\.css$/,
        include: /node_modules/,
        use: extractCSS.extract([
          'style-loader',
          'css-loader!postcss-loader',
          'resolve-url-loader'
        ]),
      },
      {
        test: /\.(png|woff|woff2|eot|ttf|svg)$/,
        use: ['url-loader?limit=100000']
      }
    ]
  }
};
`

**Comment by mjstewart** [comment]
I've consolidated all the recommendations into a single post that worked for me.

1. Ensure you have installed 
`yarn save --dev url-loader file-loader css-loader style-loader`

2. Basic webpack config only relating to adding semantic-ui-css. I followed the guide from https://github.com/webpack-contrib/css-loader. You don't need sass loaders given its already a minified css file.

Note:
- The css loader inclues node modules, `include: /node_modules/`
- postcss is optional

```javascript
module.exports = {
  module: {
    rules: [
      {
        test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 100000,
          },
        },
      },
      {
        test: /\.css$/,
        include: /node_modules/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: [
            {
              loader: 'css-loader',
            },
            {
              loader: 'postcss-loader',
            },
          ],
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("styles.css"),
  ]
}
 ```

3. import 'semantic-ui-css/semantic.min.css'; in your index.js file.

**Comment by johnnykoo84** [comment]
@mjstewart 

Thank you for your complete guide MJ, I tried to follow your guid step by step. 

Now I get a different error. 
The main issue seems like 'postcss-smart-import' is missing. Any of your enlightenings will be very much appreciated. 

`
ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib?{}!./node_modules/semantic-ui-css/semantic.min.css
Module build failed: Error: Cannot find module 'postcss-smart-import'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.plugins (/Users/kooslab/project/scoop/webpack.dev.config.js:77:19)
    at Object.parseOptions (/Users/kooslab/project/scoop/node_modules/postcss-loader/lib/options.js:5:37)
    at Promise.resolve.then (/Users/kooslab/project/scoop/node_modules/postcss-loader/lib/index.js:64:27)
 @ ./node_modules/semantic-ui-css/semantic.min.css 4:14-109 18:2-22:4 19:20-115
 @ ./client/index.js
 @ multi ./client/index.js webpack-dev-server/client?http://0.0.0.0:3001 webpack/hot/only-dev-server ./client

ERROR in ./node_modules/semantic-ui-css/semantic.min.css
Module build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'postcss-smart-import'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.plugins (/Users/kooslab/project/scoop/webpack.dev.config.js:77:19)
    at Object.parseOptions (/Users/kooslab/project/scoop/node_modules/postcss-loader/lib/options.js:5:37)
    at Promise.resolve.then (/Users/kooslab/project/scoop/node_modules/postcss-loader/lib/index.js:64:27)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at runLoaders (/Users/kooslab/project/scoop/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/kooslab/project/scoop/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/kooslab/project/scoop/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/kooslab/project/scoop/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/Users/kooslab/project/scoop/node_modules/postcss-loader/lib/index.js:176:71)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Child extract-text-webpack-plugin:
       [0] ./node_modules/css-loader!./node_modules/postcss-loader/lib?{}!./node_modules/semantic-ui-css/semantic.min.css 647 bytes {0} [built] [failed] [1 error]
    
    ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib?{}!./node_modules/semantic-ui-css/semantic.min.css
    Module build failed: Error: Cannot find module 'postcss-smart-import'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.plugins (/Users/kooslab/project/scoop/webpack.dev.config.js:77:19)
        at Object.parseOptions (/Users/kooslab/project/scoop/node_modules/postcss-loader/lib/options.js:5:37)
        at Promise.resolve.then (/Users/kooslab/project/scoop/node_modules/postcss-loader/lib/index.js:64:27)
        at process._tickCallback (internal/process/next_tick.js:109:7)
webpack: Failed to compile.
`

**Comment by Steve3029** [comment]
@mjstewart I followed you resolution, but I've got a error. I use webpack 3.5.5 and my webpack config is following:
`const path = require('path')
const ExtractTextPlugin = require("extract-text-webpack-plugin")
// const webpack = require('webpack')


module.exports = {
  // entry: ["react-hot-loader/patch", "./app/index.js"],
  entry: "./app/index.js",
  output: {
    filename: "bundle.js",
    path: path.join(__dirname, 'dist')
  },
  plugins: [
    new ExtractTextPlugin("styles.css")
    // new webpack.HotModuleReplacementPlugin()
  ],
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_moudules/,
        use: 'babel-loader'
      },
      {
        test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 100000,
          },
        },
      },
      {
        test: /\.css$/,
        include: /node_modules/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: [
            {
              loader: 'css-loader',
            },
            {
              loader: 'postcss-loader',
            },
          ],
        })
      }
    ]
  },
  resolve: {
    extensions: ['.js', '.jsx']
  },
  devtool: 'source-map',
}`

And the error info is: 
`ERROR in ./node_modules/semantic-ui-css/semantic.min.css
Module build failed: ModuleBuildError: Module build failed: Error: No PostCSS Config found in: /home/falcon/workplace/ticket-world/node_modules/semantic-ui-css`

**Comment by hawkeng** [comment]
I finally managed to make it work, the issue was that I was trying to import semantic.min.css and since I already had a css loader was causing conflict with the font paths.

I changed my import statement to look like this
`import "semantic-ui-css/semantic.css";`

**Comment by annjawn** [comment]
Documentation is not clear on how to resolve this issue. I tried almost all the options from this thread but it still gives me this error.

**Comment by wildcookie007** [comment]
Same here, cant resolve this issue:

`Module parse failed: Unexpected character '@' (11:0)
You may need an appropriate loader to handle this file type.
@import url('https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');
| /*!`

simply by using `import 'semantic-ui-css/semantic.min.css';`

url-loader did not help,
importing semantic.css did not help
including node_modules did not help

**Comment by CalmArms** [comment]
Webpack and all the other parts are still a bit of a magic box to me, so apologies for not having more insight – but here's a setup that might work if the others haven't.

I was able to resolve the issue @wildcookie007 was getting, and another error when resolving the .png country flag images in the library by using a combination of `css-loader`, `style-loader`, and `file-loader` in the following way...

```
module: {
    rules: [{
            test: /\.js$/,
            exclude: /(node_modules|bower_componets)/,
            use: {
                loader: 'babel-loader',
                options: {
                    presets: ['@babel/preset-env', '@babel/preset-react', '@babel/preset-flow'],
                    plugins: [
                        '@babel/transform-runtime',
                        '@babel/syntax-dynamic-import',
                        '@babel/proposal-class-properties'
                    ]
                }
            }
        },
        {
            test: /\.css$/,
            use: [{
                    loader: 'style-loader'
                },
                {
                    loader: 'css-loader'
                }
            ]
        },
        {
            test: /\.(ttf|eot|svg|woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            use: [{
                loader: 'file-loader'
            }]
        },
        {
            test: /\.(png|jpg|gif)$/,
            use: [{
                loader: 'file-loader'
            }]
        }
    ]
}
```
In the root JS file of the project: `import 'semantic-ui-css/semantic.min.css'`
In the root HTML file of the project: `<link rel="stylesheet" type="text/css" href="/semantic.min.css">`

**Comment by gravey16** [comment]
Was able to install semantic-ui-css by:
create file styles.global.scss  with `@import '~semantic-ui-css/semantic.css';`
then import it in js files `import './styles/styles.global.scss'`

these are my loader
{
            test: /\.(ttf|eot|svg|woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            use: [{
                loader: 'file-loader'
            }]
        },
        {
            test: /\.(png|jpg|gif)$/,
            use: [{
                loader: 'file-loader'
            }]
        },
      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader"
          }
        ]
      },
      {
            test: /\.css$/,
            use: [{
                    loader: 'style-loader'
                },
                {
                    loader: 'css-loader'
                }
            ]
       },
      {
        test: /\.(sass|scss)$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          { loader: 'sass-loader' },
        ]
     }

hope this is helpful.  it seems to be working fine for now

**Comment by kateile** [comment]
I faced similar error for couple of days and  finally solved it this way:
**index.js**
`import 'semantic-ui-css/semantic.min.css'`

**wepack.config.js**
```
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const isProduction = typeof NODE_ENV !== 'undefined' && NODE_ENV === 'production';
const mode = isProduction ? 'production' : 'development';
// Enable sourcemaps for debugging webpack's output in development.
const devtool = isProduction ? false : 'inline-source-map';
```
```
    {
        entry: ["@babel/polyfill", "./src/views/client/client.js"],
        target: 'web',
        mode,
        devtool,
        module: {
            rules: [
                {
                    test: /\.(js|jsx)$/,
                    use: 'babel-loader',
                    exclude: /node_modules/,
                },
                // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
                {
                    enforce: "pre",
                    test: /\.js$/,
                    loader: "source-map-loader"
                },
                // Assets
                {
                    test: /\.(png|woff|woff2|eot|ttf|svg)$/,
                    loader: 'url-loader?limit=100000'
                },
                // CSS Files
                {
                    test: /\.css$/,
                    use: [
                        {
                            loader: MiniCssExtractPlugin.loader,
                            options: {
                                publicPath: (resourcePath, context) => {
                                    // publicPath is the relative path of the resource to the context
                                    // e.g. for ./css/admin/main.css the publicPath will be ../../
                                    // while for ./css/main.css the publicPath will be ../
                                    return path.relative(path.dirname(resourcePath), context) + '/';
                                },
                            },
                        },
                        'css-loader'
                    ]
                }
            ]
        },
        output: {
            filename: 'client.js',
            path: path.join(__dirname, 'dist', 'public')
        },
        plugins: [
            new MiniCssExtractPlugin({
                // Options similar to the same options in webpackOptions.output
                // both options are optional
                filename: '[name].css',
                chunkFilename: '[id].css',
            }),
        ]
    },
```
