### ISSUE TITLE
Missing assets from when integrating with webpack 2

### ISSUE THREAD

**Issue by mersocarlin** [Semantic-Org/Semantic-UI-CSS#30]
I'm getting an error from `style-loader` when attempting to integrate `webpack 2` and `semantic-ui-css`.
It throws an error due to the missing `assets` folder from default semantic-ui theme

webpack version: 2.2.1
semantic-ui-css version: 2.2.8

<img width="574" alt="screen shot 2017-02-21 at 19 52 25" src="https://cloud.githubusercontent.com/assets/3759165/23179776/58635594-f86f-11e6-8ed8-9e67e4cccf02.png">

**Comment by mersocarlin** [comment]
What have you guys done from version 2.2.7 to 2.2.8? 

Event the main js `semantic.js` file is broken 👎

**Comment by jlukic** [comment]
It looks like the assets folder got nerfed by the build script
https://github.com/Semantic-Org/Semantic-UI-CSS/tree/3d593b211aba01ff137886432a069ed0087ec973

**Comment by jlukic** [comment]
Actually just pushed as `2.2.9`

**Comment by mersocarlin** [comment]
Just noticed that #29 is related

**Comment by mersocarlin** [comment]
Thanks @jlukic 👍
