### ISSUE TITLE
Disable web fonts

### ISSUE THREAD

**Issue by jgoodall** [Semantic-Org/Semantic-UI-CSS#31]
Is there any way to turn off the web font import, below, in the css file, other than just removing it? We have customers that are in a closed environment.

```
@import url('https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');
```

**Comment by davewarfel** [comment]
If you are using Gulp to build your files, you can add the following line to your `/src/site/globals/site.variables` file, and that will completely remove the `@import` of the Lato Google Font.

`@importGoogleFonts : false;`

Reference: https://github.com/Semantic-Org/Semantic-UI/issues/1305

**Comment by jgoodall** [comment]
We dont use gulp, we install from `npm` and use webpack.

**Comment by jgoodall** [comment]
ok thanks.

**Comment by ifritmitsuma** [comment]
Actually, this project is `semantic-ui-css`, so it's not possible to use `site.variables`, right?
How would one possibly use this project offline, importing the font locally, without having to change the code directly after `npm install`?

**Comment by vphantom** [comment]
I'm toying with the idea of doing a `grep -v 'font-face:'` on each file I need, but short of that if one is satisfied with Lato, an option is to use PostCSS with [the Assets plugin](https://github.com/borodean/postcss-assets) to force inlining the font into a CSS file you're building locally.

**Comment by arthurlacoste** [comment]
I have made a fork for this issue : https://github.com/arthurlacoste/semantic-ui-offline

You cant use this for the css with fonts includes : 
```js
npm i semantic-ui-offline
```

**Comment by brianespinosa** [comment]
Thanks @arthurlacoste.

**Comment by lubber-de** [comment]
Lato 2.0 fonts bundled and googlefont import removed in the official community fork https://fomantic-ui.com by
https://github.com/fomantic/Fomantic-UI/pull/2359
