### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by rcauquil** [Semantic-Org/Semantic-UI-CSS#5]
Hi,

Since yesterday jQuery seems to be undefined.. I tried with a fresh new project, same issue.

Have a good day

**Comment by jlukic** [comment]
jQuery is [a dependency](https://github.com/Semantic-Org/Semantic-UI-CSS/blob/master/package.json#L17), you must include this yourself.

**Comment by rcauquil** [comment]
That's what I did before... 
Actually the add order was important, I had to remove both jquery and semantic then reset the project and add jquery before semantic..
Thanks

**Comment by mjesuele** [comment]
The same thing happened to me and rcauqull's solution worked for me too. jlukic, I didn't quite understand what you were getting at. Would it be possible for you to clarify? Thanks!

**Comment by rcauquil** [comment]
Also, jQuery is included by default so there is no need to add it as a package.
"This package is automatically included in every new Meteor app by meteor create." (from the jquery package page).
Version seems to be 1.11.2 (on my app)

**Comment by jlukic** [comment]
Ohh you're specifically talking about the use of this repo as a meteor package. I was assuming NPM.
