### ISSUE TITLE
[ React, Webpack, yarn ] Module not found: Can't resolve '../themes/default/assets/fonts/brand-icons.eot'

### ISSUE THREAD

**Issue by dimitar-nikovski** [Semantic-Org/Semantic-UI-CSS#52]
**Webpack error:**

Failed to compile.

./node_modules/semantic-ui-css/components/icon.min.css
Module not found: Can't resolve '../themes/default/assets/fonts/brand-icons.eot' in 'H:\student-voice-client\studentvoice\node_modules\semantic-ui-css\components'.

Just for future reference, this resulted from using Webpack and yarn and if yarn autoclean is enabled with the default settings by running:

`yarn autoclean --init`

You could either change the settings in `.yarnclean` or delete it and re-run:

`yarn add semantic-ui-css`

**Comment by hytromo** [comment]
For future reference, in order to solve this problem using semantic ui, I had to run

`gulp build-assets` and then run `gulp build` inside the semantic folder.

For some reason, only running `gulp build` resulting in only `icons.*` to be inside the assets folder and `brand-icons.*` were missing.

**Comment by MikeBroders** [comment]
yarn autoclean added these two entries in the .yarnclean file

# asset directories
images
assets

remove them and reinstall semantic-ui-css and enjoy the theme assets
