### ISSUE TITLE
Wrong CSS syntax for background-color

### ISSUE THREAD

**Issue by ppaczkowski** [Semantic-Org/Semantic-UI-CSS#56]
You are using kinda shady syntax for background-color. I have to import components manually for widgets and my devtools are not happy about that. 
`background-color: none #FFFFFF !important;`
Example in release:
(https://github.com/Semantic-Org/Semantic-UI-CSS/blob/master/components/label.css#L990)

Fix:
1. One parameter too many. Good: `background-color: #FFFFFF !important;` or `background-color: transparent !important;`
2. Using "none" with background-color is a bad idea(If you have to then use "transparent" instead).
Look here (https://stackoverflow.com/questions/8739665/is-background-colornone-valid-css)
![1](https://user-images.githubusercontent.com/36645263/42103897-e399d536-7bca-11e8-876e-32021f3eebd4.jpg)

**Comment by pdfowler** [comment]
Visible side effect of this is on a basic green label. Rather than rendering a label with a green outline and green text, it is rendered as a solid block of green (with nice round corners) 😡

**Comment by OwenPattison** [comment]
Its just invalid css - bakcground-color takes a single property which is <color>.
Attempting to use 2 is incorrect, also 'none' is not valid as a background-color, i've tried opening a PR to fix this issue but got this:
![image](https://user-images.githubusercontent.com/5864244/42441358-d906e748-835f-11e8-9dc0-4a5133cb078c.png)

**Comment by ppaczkowski** [comment]
Okay. Issue is handled here https://github.com/Semantic-Org/Semantic-UI/issues/6439.
I am closing this one.
