### ISSUE TITLE
jQuery dependency must be explicitly declared

### ISSUE THREAD

**Issue by apendua** [Semantic-Org/Semantic-UI-CSS#8]
... otherwise we will keep getting errors like this:

![zrzut ekranu 2015-03-19 o 09 16 27](https://cloud.githubusercontent.com/assets/1971195/6726527/be4b2194-ce18-11e4-8b3b-8e5238c839b1.png)

**Comment by lb-** [comment]
+1

**Comment by apendua** [comment]
The current workaround is to put `jquery` package before `semantic:ui-css` on the list of packages in `.meteor/packages` file.

**Comment by jlukic** [comment]
How would you do this in `package.js`? Actually include jquery in the repo and `addFile` it?

**Comment by apendua** [comment]
Like this:
```
api.use('jquery', 'client');
```

**Comment by apendua** [comment]
`jquery` is actually a core Meteor package

**Comment by jlukic** [comment]
Fixed in publish script, will update with next version tick
https://github.com/Semantic-Org/Semantic-UI/commit/893d6887931ddfc783e9e6ddd963d337d4c80668
