### ISSUE TITLE
Form Validation breaking submit event

### ISSUE THREAD

**Issue by Aselox** [Semantic-Org/Semantic-UI-CSS#9]
Hello,
I just found out that while using the form validation feature of semantic ui by adding a js code like the following to the page, Meteor is not able to get the submit event from the form anymore. Removing the code solves the issue.
```javascript
$('.ui.form')
        .form({
            email: {
                identifier: 'email',
                rules: [
                    {
                        type: 'empty',
                        prompt: 'Please enter a valid email'
                    }
                ]
            },
            password: {
                identifier: 'password',
                rules: [
                    {
                        type: 'empty',
                        prompt: 'Please enter a password'
                    }
                ]
            }
        });
```
Is this a bug or something wrong on my end?
Thank you

**Comment by avalanche1** [comment]
I've just found out that semantic ui overrides meteor events. So instead of capturing events in meteor, use semantic callbacks:
![image](https://cloud.githubusercontent.com/assets/10534563/7428342/fdd42da2-efff-11e4-9e81-b5711d48cbd5.png)
